CREATE TABLE movies (
  id INTEGER PRIMARY KEY,
  name VARCHAR (255) NOT NULL,
  description TEXT NOT NULL,
  release_date TIMESTAMP NOT NULL,
  rating VARCHAR (255) NOT NULL,
  poster_url VARCHAR (255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
