CREATE TABLE actors (
  id SERIAL PRIMARY KEY,
  name VARCHAR (255) NOT NULL,
  biography TEXT NOT NULL,
  profile_url VARCHAR (255),
  birth_date TIMESTAMP NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
